name: Release
on:
  push:
    branches:
      - main
env:
  CI: true
jobs:
  release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install dependencies
        env:
          PNPM_CACHE_FOLDER: .pnpm-store
        run: |
          npm i pnpm@latest -g
          pnpm config set store-dir $PNPM_CACHE_FOLDER
          pnpm i
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm release --filter react-mobile-router
